# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

seeds = [
  {
    name: "Colorful Marigold Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Organic Cabbage Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Non-GMO Chives Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Rare Specialty Orange Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Native Blueberry Bush Seeds",
    plant_type: "Shrubs",
    growing_season: "Spring",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 452,
  },
  {
    name: "Drought-Tolerant Bermuda Grass Seeds",
    plant_type: "Grasses",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 113,
  },
  {
    name: "Heirloom Daisy Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Organic Spinach Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Wildlife-Attracting Lemongrass Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Pollinator-Friendly Cherry Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Fragrant Lavender Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 226,
  },
  {
    name: "Juicy Tomato Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 452,
  },
  {
    name: "Aromatic Mint Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Apple Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Rhododendron Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Sturdy Bamboo Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunny Sunflower Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Crunchy Carrot Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Fragrant Rosemary Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Peachy Peach Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Tulip Delight Flower Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Healthy Broccoli Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Fragrant Sage Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Delicious Pear Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Lilac Bush Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Green Bamboo Shoot Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunny Day Sunflower Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Bell Pepper Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Thyme Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Pomegranate Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Radiant Roses Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Zesty Zucchini Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Aromatic Basil Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Cherry Blossom Delight Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Exquisite Azalea Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Tropical Palm Bamboo Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunny Day Lily Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Sweet Crunchy Carrot Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Rosemary Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Peachy Delight Peach Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Vivid Iris Flower Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Healthy Cucumber Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Aromatic Oregano Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Exotic Mango Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Azalea Bush Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Healthy Wheat Grass Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunshine Marigold Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Crispy Lettuce Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Lavender Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Cherry Blossom Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
]

seeds.each do |data|
  tags = ""
  data.each do |k,v|
    break if k == :price
    tags = tags + " " + v.downcase
  end
  seed = Seed.new(data)
  seed.update(tags: tags)
  seed.save
end

banners = [
  {
    banner_name: "placeholder",
    image_link: "https://placehold.co/900x400",
    banner_link: "/"
  },
  {
    banner_name: "placeholder",
    image_link: "https://placehold.co/900x400",
    banner_link: "/"
  },
  {
    banner_name: "placeholder",
    image_link: "https://placehold.co/900x400",
    banner_link: "/"
  },
]

banners.each {|data| Banner.create(data)}
